[phases.setup]
nixPkgs = [
    "python312",
    "libreoffice",
    "libreoffice-still",
    "ghostscript"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "chmod +x docker-entrypoint.sh"
]

[start]
cmd = "sh docker-entrypoint.sh"