# Generated by Django 5.2.7 on 2025-10-29 02:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Estudiante')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('tipo_participante', models.CharField(choices=[('ponente', 'Ponente'), ('asistente', 'Asistente'), ('organizador', 'Organizador'), ('sponsor', 'Sponsor')], max_length=20, verbose_name='Tipo de Participante')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código Único')),
                ('archivo_pdf', models.BinaryField(help_text='PDF almacenado en base de datos', verbose_name='Archivo PDF')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('veces_descargado', models.IntegerField(default=0, verbose_name='Veces Descargado')),
                ('ultima_descarga', models.DateTimeField(blank=True, null=True, verbose_name='Última Descarga')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='app_Certigen.estudiante')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='LogDescarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas', to='app_Certigen.certificado')),
            ],
            options={
                'verbose_name': 'Log de Descarga',
                'verbose_name_plural': 'Logs de Descargas',
                'ordering': ['-fecha_descarga'],
            },
        ),
    ]
