# Generated by Django 5.2.7 on 2025-10-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Certigen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='archivo_pdf',
            field=models.BinaryField(blank=True, help_text='Certificado en formato PDF', null=True, verbose_name='Archivo PDF'),
        ),
    ]
